%Author : Sarav Shah

%This program will take in your peaks and times, from Phase_peakFinder
%program and display them in two columns. The first column being your peak
%times and the second column being your peak intensity values. 

%Determine number of columns you are parsing through.
for i = 1:8
        
    %Grabs the peaks and times that were generated by the Phase_peakfinder
        peaks = eval(sprintf('P%d',i));
        time = eval(sprintf('T%d',i));
    %Reshape the peak intensities and times to become rows.
        formatted_peaks = reshape(peaks.',1,[]);
        formatted_time = reshape(time.',1,[]);
        
        
       %combine the peaks and times to become two rows
        combine_both = [formatted_time.' formatted_peaks.'];
        
        combine_both(combine_both == 0) = NaN;
        combine_both = combine_both(~isnan(combine_both(:,2)),:);
        
        eval(sprintf ('Final%d = [finalfile]', i));
        combine_both = combine_both(~isnan(combine_both(:,2)),:);
        
      
end

clearvar -except Final1 Final2 Final3 Final4 Final5 Final6 Final7 Final8
